#!/bin/bash
# Project Initializer Script
# Generated by project-initializer skill
# Usage: bash init-project.sh [project-name] [stack]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
PROJECT_NAME="${1:-my-project}"
STACK="${2:-vite-tanstack}"
PKG_MANAGER="${3:-bun}"

echo -e "${BLUE}=== Project Initializer ===${NC}"
echo -e "Project: ${GREEN}$PROJECT_NAME${NC}"
echo -e "Stack: ${GREEN}$STACK${NC}"
echo -e "Package Manager: ${GREEN}$PKG_MANAGER${NC}"
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check package manager
check_package_manager() {
    case $PKG_MANAGER in
        bun)
            if ! command_exists bun; then
                echo -e "${YELLOW}Bun not found. Installing...${NC}"
                curl -fsSL https://bun.sh/install | bash
            fi
            ;;
        pnpm)
            if ! command_exists pnpm; then
                echo -e "${YELLOW}pnpm not found. Installing...${NC}"
                npm install -g pnpm
            fi
            ;;
        npm)
            # npm comes with Node.js
            ;;
    esac
}

# Create project based on stack
create_project() {
    case $STACK in
        vite-tanstack)
            echo -e "${BLUE}Creating Vite + TanStack Router project...${NC}"
            if [ "$PKG_MANAGER" = "bun" ]; then
                bun create vite "$PROJECT_NAME" -- --template react-ts
            else
                $PKG_MANAGER create vite@latest "$PROJECT_NAME" -- --template react-ts
            fi
            cd "$PROJECT_NAME"

            # Install TanStack Router
            $PKG_MANAGER add @tanstack/react-router
            $PKG_MANAGER add -D @tanstack/router-devtools @tanstack/router-plugin

            # Install TanStack Query
            $PKG_MANAGER add @tanstack/react-query
            $PKG_MANAGER add -D @tanstack/react-query-devtools

            # Install shadcn/ui
            npx shadcn@latest init -y
            npx shadcn@latest add button input table form dialog select card tabs

            # Install additional deps
            $PKG_MANAGER add @supabase/supabase-js zustand
            $PKG_MANAGER add react-hook-form @hookform/resolvers zod
            $PKG_MANAGER add clsx tailwind-merge lucide-react date-fns
            ;;

        remix)
            echo -e "${BLUE}Creating Remix project...${NC}"
            npx create-remix@latest "$PROJECT_NAME" --yes
            cd "$PROJECT_NAME"

            # Install shadcn/ui
            npx shadcn@latest init -y
            npx shadcn@latest add button input table form dialog select card tabs

            # Install additional deps
            $PKG_MANAGER add @supabase/supabase-js @supabase/ssr zustand
            $PKG_MANAGER add react-hook-form @hookform/resolvers zod
            $PKG_MANAGER add clsx tailwind-merge class-variance-authority
            $PKG_MANAGER add lucide-react date-fns nanoid
            ;;

        umi-antd-pro)
            echo -e "${BLUE}Creating UmiJS + Ant Design Pro project...${NC}"
            npm create umi -- "$PROJECT_NAME"
            cd "$PROJECT_NAME"

            $PKG_MANAGER add @supabase/supabase-js
            $PKG_MANAGER add date-fns lodash-es
            $PKG_MANAGER add -D @types/lodash-es
            ;;

        expo-nativewind)
            echo -e "${BLUE}Creating Expo + NativeWind project...${NC}"
            npx create-expo-app "$PROJECT_NAME" -t expo-template-blank-typescript
            cd "$PROJECT_NAME"

            $PKG_MANAGER add nativewind
            $PKG_MANAGER add -D tailwindcss
            npx tailwindcss init

            $PKG_MANAGER add @tanstack/react-query @supabase/supabase-js zustand
            ;;

        monorepo)
            echo -e "${BLUE}Creating Bun + Turborepo monorepo...${NC}"
            bunx create-turbo@latest "$PROJECT_NAME"
            cd "$PROJECT_NAME"
            ;;

        *)
            echo -e "${RED}Unknown stack: $STACK${NC}"
            exit 1
            ;;
    esac
}

# Create project structure
create_structure() {
    echo -e "${BLUE}Creating project structure...${NC}"
    local TODAY
    TODAY="$(date +%Y-%m-%d)"

    mkdir -p docs/architecture
    mkdir -p docs/reference-configs
    mkdir -p tasks
    mkdir -p .ops
    mkdir -p artifacts

    # Create documentation files
    cat > docs/PROGRESS.md << EOF
# Development Progress

## Current Sprint

### In Progress
- [ ] Initial project setup

### Completed
- [x] Project initialized

## Next Steps
1. Configure environment variables
2. Set up database schema
3. Implement first feature

---
*Last updated: ${TODAY}*
EOF

    cat > docs/CHANGELOG.md << 'EOF'
# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased]

### Added
- Initial project setup

---
*Format based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)*
EOF

    cat > tasks/todo.md << EOF
# Task Execution Checklist (Primary)

## Plan
- [ ] Define scope and acceptance criteria
- [ ] Break down into checkable tasks

## Execution
- [ ] Implement task 1
- [ ] Implement task 2

## Review Section
- Verification evidence:
- Behavior diff notes:
- Risks / follow-ups:

---
*Updated: ${TODAY}*
EOF

    cat > tasks/lessons.md << EOF
# Lessons Learned (Self-Improvement Loop)

## Template
- Date:
- Triggered by correction:
- Mistake pattern:
- Prevention rule:
- Where to apply next time:

---
*Updated: ${TODAY}*
EOF

    cat > docs/TODO.md << EOF
# TODO List (Legacy Compatibility)

Primary execution checklist has moved to `tasks/todo.md`.
Keep this file only for legacy tools that still read docs/TODO.md.

---
*Updated: ${TODAY}*
EOF

    cat > docs/plan.md << EOF
# Deep Plan Notes (Compatibility)

Use this file for detailed architecture/spec context.
Primary execution checklist lives in `tasks/todo.md`.

---
*Updated: ${TODAY}*
EOF

    cat > docs/reference-configs/changelog-versioning.yaml.md << 'EOF'
# Changelog & Versioning Reference

Use this file for detailed release-note and semantic-versioning rules.
EOF

    cat > docs/reference-configs/git-strategy.yaml.md << 'EOF'
# Git Strategy Reference

Use this file for branch model and commit convention details.
EOF

    cat > docs/reference-configs/release-deploy.yaml.md << 'EOF'
# Release & Deployment Reference

Use this file for release pipeline and deployment trigger details.
EOF

    cat > docs/reference-configs/ai-workflows.yaml.md << 'EOF'
# AI Workflows Reference

Use this file for extended AI workflow templates and session handoff protocols.
EOF

    # Update .gitignore
    cat >> .gitignore << 'EOF'

# Project-specific
.*/
artifacts/
*.tar.gz
*.tgz

# Environment
.env
.env.*
!.env.example

# OS metadata
.DS_Store
EOF

    # Create .env.example
    cat > .env.example << 'EOF'
# Supabase
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key

# Optional: Service Role (server-side only)
# SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

# App Config
NODE_ENV=development
PORT=3000
EOF

    echo -e "${GREEN}Project structure created!${NC}"
}

# Install dev tools
install_dev_tools() {
    echo -e "${BLUE}Installing dev tools...${NC}"

    # Biome (Linting & Formatting)
    $PKG_MANAGER add -D @biomejs/biome

    # Testing
    $PKG_MANAGER add -D vitest @testing-library/react @testing-library/jest-dom

    # Initialize Biome
    npx @biomejs/biome init

    echo -e "${GREEN}Dev tools installed!${NC}"
}

# Main execution
main() {
    check_package_manager
    create_project
    create_structure
    install_dev_tools

    echo ""
    echo -e "${GREEN}=== Project initialized successfully! ===${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. cd $PROJECT_NAME"
    echo "  2. Copy .env.example to .env and configure"
    echo "  3. Run: $PKG_MANAGER run dev"
    echo "  4. Add checklist to tasks/todo.md"
    echo "  5. Capture corrections in tasks/lessons.md"
    echo ""
}

main
